default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: test_app_pass
  pool: 5

development:
  <<: *default
  database: test_app_development

test:
  <<: *default
  database: test_app_test

production:
  <<: *default
  database: test_app_production
  username: <%= ENV["TEST_APP_DATABASE_USER"] %>
  host: <%= ENV["TEST_APP_DATABASE_HOST"] %>
  password: <%= ENV["TEST_APP_DATABASE_PASSWORD"] %>
